package io.github.lbarnkow.jarb.misc;

public enum EventTypes {
	REALTIME_SESSION_CLOSED, //
	ACQUIRED_LEADERSHIP, //
	LOST_LEADERSHIP, //
	REALTIME_SESSION_ESTABLISHED, //
	AUTH_TOKEN_REFRESHED, //
	NEW_SUBSCRIPTION, //
	PROCESS_ROOM
}